preferred_syntax = :sass
http_path = '/'
css_dir = '../../public/assets/stylesheets'
sass_dir = 'sass'
images_dir = '../../public/images'
javascripts_dir = '../../public/javascripts'
relative_assets = true
line_comments = true
# output_style = :compressed
